[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "inv_plts"
version = "2025.01.22"
dependencies = [
    "kivy",
    "opencv-python",
    "ipykernel",
    "buildozer",
]
requires-python = ">3.9"
authors = []
maintainers = []
description = "Invasive plants project for data collection, preprocessing, model training, and deployment."
readme = "README.md"
#license = {file = "LICENSE"}
keywords = []
classifiers = [
    "Development Status :: 4 - Beta",
    "Programming Language :: Python"
]

[project.urls]
#Homepage = ""
#Documentation = ""
Repository = "https://github.com/Imageomics/invasives-project"
#"Bug Tracker" = ""
#Changelog = ""

[tool.hatch.build.targets.wheel]
packages = ["src/inv_plts", "app"]